# Association Rules

### Data Preprocessing

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules
import warnings 
warnings.simplefilter("ignore")

In [2]:
df=pd.read_csv("Online retail.csv")
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [3]:
df.dropna()
df.drop_duplicates(inplace=True)
df.tail(15)

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
7474  turkey,mineral water,cooking oil,chocolate,fre...
7475  tomatoes,tomato sauce,spaghetti,mineral water,...
7477  turkey,ground beef,mineral water,chocolate,sou...
7478  shrimp,pasta,mineral water,olive oil,pancakes,...
7479  frozen vegetables,french wine,pancakes,french ...
7480                   chocolate,shrimp,pasta,spaghetti
7482  fresh tuna,parmesan cheese,whole wheat pasta,f...
7484               parmesan cheese,champagne,white wine
7485  red wine,tomato sauce,spaghetti,chocolate,oliv...
7489             herb & pepper,spaghetti,low fat yogurt
7492  burgers,salmon,pancakes,french fries,frozen sm...
7493  turkey,burgers,dessert wine,shrimp,pasta,tomat...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

In [26]:
df.columns=["group of things"]
splitting=df["group of things"].str.split(",").apply(lambda x:[groups.strip()for groups in x if groups])
encoder= TransactionEncoder()
df_encoder= encoder.fit(splitting).transform(splitting)
TE_data=pd.DataFrame(df_encoder,columns=encoder.columns_)
df.tail(15)

                                        group of things
7474  turkey,mineral water,cooking oil,chocolate,fre...
7475  tomatoes,tomato sauce,spaghetti,mineral water,...
7477  turkey,ground beef,mineral water,chocolate,sou...
7478  shrimp,pasta,mineral water,olive oil,pancakes,...
7479  frozen vegetables,french wine,pancakes,french ...
7480                   chocolate,shrimp,pasta,spaghetti
7482  fresh tuna,parmesan cheese,whole wheat pasta,f...
7484               parmesan cheese,champagne,white wine
7485  red wine,tomato sauce,spaghetti,chocolate,oliv...
7489             herb & pepper,spaghetti,low fat yogurt
7492  burgers,salmon,pancakes,french fries,frozen sm...
7493  turkey,burgers,dessert wine,shrimp,pasta,tomat...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

In [27]:
TE_data.tail(15)

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
5160,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
5161,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5162,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5163,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5164,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5165,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5166,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
5167,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
5168,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5169,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5171,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

### Association Rule Mining

In [28]:
frequent_things= apriori(TE_data,min_support=0.01,use_colnames=True)
frequent_things.tail(15)

      support                                 itemsets
421  0.016039       (mineral water, milk, ground beef)
422  0.013913           (milk, spaghetti, ground beef)
423  0.010821   (mineral water, pancakes, ground beef)
424  0.024734  (mineral water, spaghetti, ground beef)
425  0.012367         (mineral water, olive oil, milk)
426  0.011401          (mineral water, milk, pancakes)
427  0.011401            (mineral water, milk, shrimp)
428  0.012367              (mineral water, milk, soup)
429  0.022609         (mineral water, milk, spaghetti)
430  0.010242             (olive oil, milk, spaghetti)
431  0.014686    (mineral water, olive oil, spaghetti)
432  0.016618     (mineral water, pancakes, spaghetti)
433  0.012367       (mineral water, spaghetti, shrimp)
434  0.010821         (mineral water, spaghetti, soup)
435  0.013527     (tomatoes, mineral water, spaghetti)

In [33]:
num_itemsets = 5 

ass_rules = association_rules(frequent_things, 
                        metric="confidence", 
                        min_threshold=0.2, 
                        num_itemsets=num_itemsets) 

ass_rules = ass_rules[ass_rules['lift']>1.0]
ass_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(mineral water),0.029179,0.299710,0.010821,0.370861,1.237399,1.0,0.002076,1.113092,0.197619,0.034022,0.101602,0.203483
1,(avocado),(chocolate),0.045797,0.205217,0.010242,0.223629,1.089716,1.0,0.000843,1.023715,0.086281,0.042536,0.023165,0.136767
2,(avocado),(french fries),0.045797,0.192657,0.011594,0.253165,1.314069,1.0,0.002771,1.081019,0.250476,0.051107,0.074947,0.156673
3,(avocado),(milk),0.045797,0.170048,0.010821,0.236287,1.389528,1.0,0.003034,1.086732,0.293786,0.052780,0.079810,0.149962
4,(avocado),(mineral water),0.045797,0.299710,0.015845,0.345992,1.154421,1.0,0.002120,1.070766,0.140185,0.048066,0.066089,0.199430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"(spaghetti, shrimp)",(mineral water),0.030338,0.299710,0.012367,0.407643,1.360125,1.0,0.003274,1.182210,0.273058,0.038929,0.154126,0.224454
351,"(mineral water, soup)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,1.0,0.003147,1.139190,0.300865,0.042912,0.122183,0.185419
352,"(spaghetti, soup)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,1.0,0.004624,1.469236,0.436362,0.034956,0.319374,0.279735
353,"(tomatoes, mineral water)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,1.0,0.005586,1.265209,0.427765,0.053971,0.209617,0.224992
354,"(tomatoes, spaghetti)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,1.0,0.004550,1.276999,0.346742,0.042787,0.216914,0.248373

In [35]:
ass_rules_sorting=ass_rules.sort_values(by='lift',ascending=False)
ass_rules_sorting[['antecedents', 'consequents', 'support', 'confidence', 'lift']].tail()

,antecedents,consequents,support,confidence,lift
191,"(eggs, burgers)",(mineral water),0.011014,0.304813,1.017025
15,(burgers),(mineral water),0.034589,0.303905,1.013996
61,(cookies),(eggs),0.012754,0.210191,1.009971
270,"(mineral water, french fries)",(eggs),0.010048,0.209677,1.007503
84,(salmon),(eggs),0.011981,0.208754,1.003067

### Analysis and Interpretation

In [36]:
ass_rules_sorting.tail(15)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
10,(burgers),(chocolate),0.113816,0.205217,0.024541,0.215620,1.050689,1.0,0.001184,1.013262,0.054440,0.083333,0.013088,0.167603
92,(fresh bread),(french fries),0.059324,0.192657,0.011981,0.201954,1.048259,1.0,0.000552,1.011650,0.048940,0.049919,0.011516,0.132070
140,(hot dogs),(mineral water),0.042512,0.299710,0.013333,0.313636,1.046466,1.0,0.000592,1.020290,0.046374,0.040541,0.019886,0.179062
91,(escalope),(spaghetti),0.083865,0.229565,0.020097,0.239631,1.043849,1.0,0.000844,1.013238,0.045852,0.068511,0.013066,0.163587
319,"(spaghetti, green tea)",(mineral water),0.038454,0.299710,0.011981,0.311558,1.039530,1.0,0.000456,1.017209,0.039548,0.036730,0.016918,0.175766
8,(brownies),(mineral water),0.045024,0.299710,0.013913,0.309013,1.031039,1.0,0.000419,1.013463,0.031524,0.042056,0.013284,0.177717
9,(brownies),(spaghetti),0.045024,0.229565,0.010628,0.236052,1.028255,1.0,0.000292,1.008490,0.028774,0.040264,0.008419,0.141174
69,(cottage cheese),(spaghetti),0.042899,0.229565,0.010048,0.234234,1.020339,1.0,0.000200,1.006097,0.020827,0.038292,0.006060,0.139003
75,(ground beef),(eggs),0.135845,0.208116,0.028792,0.211949,1.018417,1.0,0.000521,1.004864,0.020927,0.091355,0.004840,0.175148
72,(fresh bread),(eggs),0.059324,0.208116,0.012560,0.211726,1.017348,1.0,0.000214,1.004580,0.018128,0.049280,0.004559,0.136040
191,"(eggs, burgers)",(mineral water),0.036135,0.299710,0.011014,0.304813,1.017025,1.0,0.000184,1.007340,0.017368,0.033908,0.007287,0.170782
15,(burgers),(mineral water),0.113816,0.299710,0.034589,0.303905,1.013996,1.0,0.000477,1.006026,0.015576,0.091280,0.005990,0.209657
61,(cookies),(eggs),0.060676,0.208116,0.012754,0.210191,1.009971,1.0,0.000126,1.002627,0.010510,0.049811,0.002621,0.135736
270,"(mineral water, french fries)",(eggs),0.047923,0.208116,0.010048,0.209677,1.007503,1.0,0.000075,1.001976,0.007822,0.040848,0.001972,0.128980
84,(salmon),(eggs),0.057391,0.208116,0.011981,0.208754,1.003067,1.0,0.000037,1.000807,0.003244,0.047256,0.000806,0.133161

### INterview Questions

#### What is Lift and how does it help analyze associations?

Lift is a metric that  helps us to assess the strength and significance of relationships between items in our data. It compares the observed co-occurrence of items (A and B) to what would be expected by random chance.

Lift > 1: Indicates a positive association, meaning A and B often appear together more frequently than expected by chance.
Lift < 1: Suggests a negative association, where A and B rarely co-occur.
Lift = 1: Implies no significant relationship between the items.

#### What is Support and how does it identify frequent itemsets?

Support is a  metric that reflects how common an itemset (combination of items) is within our data. It's calculated as the proportion of transactions containing the entire itemset relative to the total number of transactions.

High Support: Indicates a frequently occurring itemset, suggesting a potential association between the items.
Low Support: Suggests a less common combination, which might not be as interesting for analysis.

#### What is Confidence and how does it relate to prediction?

Confidence is a metric which  focuses on the predictive power of an association rule. It tells us how likely we'll find item B in a transaction if we already know item A is present.

High Confidence: Suggests a strong correlation, meaning finding A often leads to finding B as well. This can be helpful for making predictions.
Challenges of Association Rule Learning

Scalability: As datasets grow larger, the number of potential itemsets can explode, leading to significant computational demands for processing all the combinations.

Threshold Selection: Choosing the right support and confidence thresholds is crucial. Setting them too low can generate an overwhelming number of potentially irrelevant rules, while setting them too high might miss valuable insights.

Relevancy Filtering: Not all discovered rules are equally interesting or actionable. Identifying and filtering out trivial or irrelevant rules can be a challenge.